<?php
declare(strict_types=1);

/**
 * xval_ba.php -- GET /xval_ba.
 *
 * Exposes the BA cross-validation artifact (xval_ba_php.json),
 * regenerated by test_ba.php during regression. Used at defense
 * to demonstrate PHP <-> Node bit-identical xval determinism
 * (BA bestCost = 3014.4336 @ iter 621, tol = 0).
 *
 * No Node mirror -- this is a PHP-only diagnostic endpoint.
 *
 * Pure handler handleXvalBaRequest($method, $jsonPath) accepts an
 * optional explicit artifact path for unit tests (default points at
 * php-api/tests/xval_ba_php.json). Returns
 * ['status' => int, 'json' => array]:
 *   200 -- artifact decoded & returned
 *   405 -- non-GET method
 *   500 -- artifact JSON malformed
 *   503 -- artifact file missing / unreadable
 *
 * The thin entry-point also sets Cache-Control: no-store so the
 * defense demo always reflects the latest test_ba.php run.
 *
 * PHP 7.4+ compat target (Hestia VPS).
 */

/**
 * Pure handler -- testable in isolation.
 *
 * @param string      $method   Uppercase HTTP method.
 * @param string|null $jsonPath Optional explicit artifact path
 *                              (defaults to tests/xval_ba_php.json).
 * @return array                ['status' => int, 'json' => array]
 */
function handleXvalBaRequest(string $method, ?string $jsonPath = null): array
{
    if ($method !== 'GET') {
        return ['status' => 405, 'json' => ['error' => 'method_not_allowed']];
    }

    $path = $jsonPath ?? (__DIR__ . '/tests/xval_ba_php.json');

    if (!is_file($path) || !is_readable($path)) {
        return [
            'status' => 503,
            'json'   => ['error' => 'xval_artifact_unavailable'],
        ];
    }

    $raw  = file_get_contents($path);
    $data = json_decode($raw, true);
    if (!is_array($data)) {
        return [
            'status' => 500,
            'json'   => ['error' => 'xval_artifact_malformed'],
        ];
    }

    return ['status' => 200, 'json' => $data];
}

// ----------------------------------------------------------------
// Thin entry point -- only runs when this file IS the main script.
// ----------------------------------------------------------------
if (realpath(__FILE__) === realpath($_SERVER['SCRIPT_FILENAME'] ?? '')) {
    header('Content-Type: application/json; charset=utf-8');
    header('Cache-Control: no-store');  // xval artifacts always fresh

    $method = strtoupper($_SERVER['REQUEST_METHOD'] ?? 'GET');
    $resp   = handleXvalBaRequest($method);
    http_response_code($resp['status']);
    echo json_encode($resp['json']);
    exit;
}
