<?php
declare(strict_types=1);

/**
 * test_xval_ba.php -- unit tests for the GET /xval_ba handler.
 *
 * Exercises handleXvalBaRequest() in isolation. Three groups:
 *
 *   Group A: method gating (no file I/O)
 *   Group B: real artifact read (uses default path =
 *            php-api/tests/xval_ba_php.json, regenerated by test_ba.php)
 *   Group C: error branches via DI ($jsonPath argument)
 *            - C1 non-existent path     -> 503
 *            - C2 malformed JSON file   -> 500 (uses tempnam + unlink)
 *
 * Run from project root:
 *   php php-api/tests/test_xval_ba.php
 *
 * Expected: 8/8 PASS.
 *
 * NOTE: Group B requires php-api/tests/xval_ba_php.json to exist.
 * Run `php php-api/tests/test_ba.php` first if it has not yet been
 * generated; in regression order test_ba.php precedes this file so
 * the artifact is always fresh.
 */

require_once __DIR__ . '/../xval_ba.php';

$total = 0;
$pass  = 0;

function check(string $label, bool $cond): void
{
    global $total, $pass;
    $total++;
    if ($cond) {
        $pass++;
        echo "  PASS  {$label}\n";
    } else {
        echo "  FAIL  {$label}\n";
    }
}

echo "\n=== Group A: Method gating ===\n";

$resp = handleXvalBaRequest('GET');
check('A1 GET returns 200',
    $resp['status'] === 200);

$resp = handleXvalBaRequest('POST');
check('A2 POST returns 405 method_not_allowed',
    $resp['status'] === 405
    && $resp['json']['error'] === 'method_not_allowed');

$resp = handleXvalBaRequest('DELETE');
check('A3 DELETE returns 405',
    $resp['status'] === 405);

echo "\n=== Group B: Response shape (real artifact) ===\n";

$resp = handleXvalBaRequest('GET');

check('B1 response is non-empty array',
    is_array($resp['json'])
    && count($resp['json']) > 0);

check('B2 bestCost present, numeric, > 0, finite',
    isset($resp['json']['bestCost'])
    && is_numeric($resp['json']['bestCost'])
    && $resp['json']['bestCost'] > 0
    && is_finite((float)$resp['json']['bestCost']));

check('B3 bestIteration present, integer, > 0',
    isset($resp['json']['bestIteration'])
    && is_int($resp['json']['bestIteration'])
    && $resp['json']['bestIteration'] > 0);

echo "\n=== Group C: Error branches (via DI) ===\n";

// C1: non-existent path -> 503
$resp = handleXvalBaRequest('GET', '/path/that/definitely/does/not/exist.json');
check('C1 non-existent path returns 503 xval_artifact_unavailable',
    $resp['status'] === 503
    && $resp['json']['error'] === 'xval_artifact_unavailable');

// C2: malformed JSON -> 500 (tempnam + unlink for clean teardown)
$badPath = tempnam(sys_get_temp_dir(), 'xval_test_');
file_put_contents($badPath, '{"this is not valid json');
$resp = handleXvalBaRequest('GET', $badPath);
check('C2 malformed JSON returns 500 xval_artifact_malformed',
    $resp['status'] === 500
    && $resp['json']['error'] === 'xval_artifact_malformed');
@unlink($badPath);  // teardown (suppress warning if already gone)

echo "\n";
echo "================================\n";
echo "  xval_ba.php: {$pass}/{$total} PASS\n";
echo "================================\n";

exit($pass === $total ? 0 : 1);
